services:
  bridge.event_subscriber.action_activity:
    class: Bridge\EventSubscriber\ActionActivitySubscriber

  bridge.event_subscriber.response_converter:
    class: Bridge\EventSubscriber\ResponseConverter
