imports:
  - { resource: commands.yml }
  - { resource: event_subscribers.yml }
  - { resource: cache.yml }

services:
  bridge.event_dispatcher:
    class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    arguments:
      - '@service_container'
    calls:
      - [addSubscriber, ['@bridge.event_subscriber.action_activity']]

  bridge:
    alias: bridge.registry

  bridge.registry:
    class: Bridge\Registry
    arguments:
      - '@bridge.event_dispatcher'
    calls:
      - [addCachePool, ['default', '@bridge.cache.pool.default']]

  bridge.activity_collector:
    class: Bridge\Bundle\DataCollector\ActivityCollector
    arguments:
      - '@bridge.event_subscriber.action_activity'
    public: false
    tags:
      -
        name:      data_collector
        template: 'BridgeBundle:Profiler:activity'
        id:       'bridge.activity_collector'

  # Listeners
  bridge.event_listener.command_listener:
    class: Bridge\Bundle\EventListener\CommandListener
    arguments:
      - "@bridge.registry"
    tags:
      - { name: kernel.event_listener, event: console.command, method: command }

